#! /bin/sh

export DISPLAY=:0

[[ 1 = $(apm -a) ]] && exit

battery=$(apm -l)
remaining=$(apm -m)
minutes_to_hibernate="$((remaining * (battery - 7) / battery))" # fix this

[[ $battery -lt 15 ]] && notify-send -i battery -u critical "battery critical: $battery% [hibernating in: $minutes_to_hibernate minutes]" && exit

[[ $battery -lt 25 ]] && notify-send -i battery "battery low: $battery% [hibernating in $minutes_to_hibernate minutes]" && exit
