#! /bin/env bash

##############
# packages
##############
sudo apt update
sudo apt build-dep emacs
sudo apt install -y \
     	 	 cron \
	         curl \
		 fonts-inconsolata \
		 feh \
        	 git \
        	 gpg \
        	 i3 \
        	 i3lock \
        	 i3status \
        	 isync \
        	 keepassxc \
             	 libgccjit-10-dev \
             	 libgccjit0 \
        	 mpv \
        	 msmtp \
        	 mu4e \
        	 pass \
		 pinentry-gtk2 \
		 redshift \
		 rsync \
        	 software-properties-common \
        	 syncthing \
		 vrms \
        	 wget \
		 x11-xkb-utils \
        	 xautolock \
        	 zathura 

##############
# development
##############
# pyenv
curl https://pyenv.run | bash

# poetry
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

# rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
		 



