#! /bin/sh 

PASSWORD_STORE=~/.password-store

cd $PASSWORD_STORE 

rg --files | rg .gpg -r "" | fzf --delimiter / --with-nth -1 \
    --bind "ctrl-p:execute*nohup pass -c {} >/dev/null 2>&1*+abort" \
    --bind "ctrl-u:execute*nohup pass -c2 {} >/dev/null 2>&1*+abort"
