#! /bin/env bash

# reminders:
# [] enable internet:
# su, then wpa_passphrase <ssid> <password> >> /etc/wpa_supplicant/wpa_supplicant.conf
# then enable the dhcpcd and wpa_supplicant services
# [] ensure my user is in group wheel and that wheel is enabled in visudo
# [] ensure power programs are passwordless in visudo
# [] setup syncthing

test_ip="8.8.8.8"
test_count=1

if ping -c ${test_count} ${test_ip} > /dev/null; then
    echo "Internet connection found..."
else
    echo "No internet connection so exiting..."
    echo "Run $ su then $ wpa_passphrase <ssid> <password> >> /etc/wpa_supplicant/wpa_supplicant.conf"
    echo "Then enable dchcpd and wpa_passphrase services."
    exit 1
fi

sudo xbps-install -Suv # get updates
sudo xbps-install -Sy \ 
                  acpi \
                  alsa-utils \
                  base-devel \
                  brillo \
                  cmake \                                       
                  curl \             
                  dbus \
                  dmenu \
                  elogind \
                  feh \
                  ffmpeg \
                  firefox \
                  font-go-ttf \
                  gcc \
                  git \
                  gnupg2 \
                  herbe \
                  i3lock \
                  isync \
                  keepassxc \
                  make \
                  msmtp \
                  mu4e \
                  nano \
                  pass \
                  pinentry-gtk \
                  pipewire \
                  pulseaudio-utils \
                  redshift \
                  ripgrep \
                  rustup \
                  setxkbmap \
                  starship \
                  syncthing \
                  tlp \
                  wget \
                  xautolock \
                  xorg-fonts \
                  xorg-minimal \
                  xrdb \
                  xset \
                  xsetroot

# preliminarily setup gpg2 and git
./make-gpg-git-configs
		  
# enable system services. Elogind and dbus handles the XDG_RUNTIME_DIR
# variable, which is a headache to deal with otherwise. acpid is
# disabled so that it doesn't conflict with elogind. Tlp helps with
# battery life on laptops.
sudo rm -rf /var/service/acpid
sudo ln -s /etc/sv/dbus /var/service
sudo ln -s /etc/sv/elogind /var/service
sudo ln -s /etc/sv/tlp /var/service

# install pyenv and poetry from their web installers
curl https://pyenv.run | bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -

# install rust
rustup-init

# install dwm
sudo xbps-install -Sy \
                  libX11-devel \
                  libXft-devel \
                  libXinerama-devel

mkdir -p ~/source && cd ~/source
git clone https://github.com/jsbmg/snafu
cd ~/source/snafu && cargo install --path . # for status line
cd ..
git clone https://github.com/jsbmg/dwm
cd ~/source/dwm && sudo make clean install
cd $HOME

# install emacs
# libgccjit must be manually installed
# maybe i will make a script for it

sudo xbps-install -Sy \ # install build dependencies
                  libjpeg-turbo-devel \
	          tiff-devel \
	          giflib-devel \
	          libpng-devel \
	          libXpm-devel \
	          librsvg-devel \
	          libmagick-devel \
	          libxml2-devel \
	          gnutls-devel \
	          alsa-lib-devel \
	          m17n-lib-devel \
	          jansson-devel \
	          harfbuzz-devel \
	          cairo-devel \
	          gmp-devel
	     
cd ~/source
git clone https://git.savannah.gnu.org/git/emacs.git
cd emacs
./autogen.sh
./configure --with-native-compilation --with-mailutils
make
sudo make install
cd $HOME


     
     
     

     
     

